#!/usr/bin/env ruby

require "bundler/inline"
gemfile do
  source "https://rubygems.org"
  gem "multi_repo", require: "multi_repo/cli", path: File.expand_path("../..", __dir__)
end

opts = Optimist.options do
  opt :org, "The org to list the repos for", :type => :string, :required => true
end

puts MultiRepo::Service::Github.org_repo_names(opts[:org])
