#!/usr/bin/env ruby

SCRIPT_DIR = File.expand_path("../scripts", __dir__)

def usage
  puts "Usage: multi_repo <script> [args]"
  puts "  script      Script to run"
  puts "  args        Arguments to pass to the script"
  puts "  -h, --help  Show this help message"

  available_scripts = Dir.children(SCRIPT_DIR).sort.map { |f| "  #{f}"}
  puts
  puts "Available scripts:"
  puts available_scripts
end

script, args = ARGV[0], ARGV[1..]

if script.nil? || script.empty? || script == "--help" || script == "-h"
  usage
  exit
end

fq_script = File.join(SCRIPT_DIR, script)
unless File.exist?(fq_script)
  puts "ERROR: script #{script.inspect} not found"
  puts
  usage
  exit 1
end

exec fq_script, *args
