#!/usr/bin/env ruby

require "bundler/inline"
gemfile do
  source "https://rubygems.org"
  gem "multi_repo", require: "multi_repo/cli", path: File.expand_path("..", __dir__)
end

opts = Optimist.options do
  opt :labels, "The labels to delete.", :type => :strings, :required => true

  MultiRepo::CLI.common_options(self, :repo_set_default => nil)
end
opts[:repo] = MultiRepo::Helpers::Labels.all.keys.sort unless opts[:repo] || opts[:repo_set]

github = MultiRepo::Service::Github.new(dry_run: opts[:dry_run])

MultiRepo::CLI.each_repo(**opts) do |repo|
  opts[:labels].each do |label|
    puts "Deleting #{label.inspect}"
    github.delete_label!(repo.name, label)
  end
end
