#!/usr/bin/env ruby

require "bundler/inline"
gemfile do
  source "https://rubygems.org"
  gem "multi_repo", require: "multi_repo/cli", path: File.expand_path("..", __dir__)
end
require "more_core_extensions/core_ext/array/tableize"

Optimist.options do
  synopsis "Display the current GitHub rate limit."
end

puts [MultiRepo::Service::Github.client.rate_limit.to_h].tableize
