#!/usr/bin/env ruby

require "bundler/inline"
gemfile do
  source "https://rubygems.org"
  gem "multi_repo", require: "multi_repo/cli", path: File.expand_path("..", __dir__)
end

opts = Optimist.options do
  synopsis "Merge a set of pull requests, also setting assignee and labels."

  opt :prs,      "The list of PRs to merge",           :type => :strings, :required => true
  opt :assignee, "GitHub user to assign when merging", :type => :string,  :required => true
  opt :labels,   "Labels to apply when merging",       :type => :strings

  MultiRepo::CLI.common_options(self)
end

# TODO: Normalize any PR format to `org/repo#pr`
PR_REGEX = %r{^([^/#]+/[^/#]+)#([^/#]+)$}
Optimist.die :prs, "must be in the form `org/repo#pr`" unless opts[:prs].all? { |pr| pr.match?(PR_REGEX) }

github = MultiRepo::Service::Github.new(:dry_run => opts[:dry_run])

opts[:prs].each do |pr|
  puts MultiRepo::CLI.header(pr)

  repo_name, pr_number = PR_REGEX.match(pr).captures

  begin
    github.merge_pull_request(repo_name, pr_number)
  rescue Octokit::MethodNotAllowed => err
    raise unless err.to_s.include?("Pull Request is not mergeable")

    puts "** WARN: Pull Request is not mergeable".light_yellow
  end

  github.add_labels_to_an_issue(repo_name, pr_number, opts[:labels]) if opts[:labels].present?
  github.assign_user(repo_name, pr_number, opts[:assignee])

  puts
end
