#!/usr/bin/env ruby

require "bundler/inline"
gemfile do
  source "https://rubygems.org"
  gem "multi_repo", require: "multi_repo/cli", path: File.expand_path("..", __dir__)
end

opts = Optimist.options do
  synopsis "Add or remove labels on a set of pull requests."

  opt :prs,    "The list of PRs to label", :type => :strings, :required => true
  opt :add,    "Labels to add",            :type => :strings
  opt :remove, "Labels to remove",         :type => :strings

  opt :comment, "Comment explaining the label change", :type => :string

  MultiRepo::CLI.common_options(self, :only => :dry_run)
end

Optimist.die "at least one of --add or --remove is required" unless opts[:add_given] || opts[:remove_given]

# Normalize any PR format to `org/repo#pr`
opts[:prs].map! do |pr|
  pr.sub("https://github.com/", "").sub("/pull/", "#")
end

PR_REGEX = %r{^([^/#]+/[^/#]+)#([^/#]+)$}
Optimist.die :prs, "must be in the form `org/repo#pr`" unless opts[:prs].all? { |pr| pr.match?(PR_REGEX) }

github = MultiRepo::Service::Github.new(:dry_run => opts[:dry_run])

opts[:prs].each do |pr|
  puts MultiRepo::CLI.header(pr)

  repo_name, pr_number = PR_REGEX.match(pr).captures

  github.add_labels_to_an_issue(repo_name, pr_number, opts[:add]) if opts[:add].present?
  github.remove_labels_from_an_issue(repo_name, pr_number, opts[:remove]) if opts[:remove].present?
  github.add_comment(repo_name, pr_number, opts[:comment]) if opts[:comment].present?

  puts
end
