#!/usr/bin/env ruby

require "bundler/inline"
gemfile do
  source "https://rubygems.org"
  gem "multi_repo", require: "multi_repo/cli", path: File.expand_path("..", __dir__)
end

opts = Optimist.options do
  synopsis "Reenable all disabled workflows in an org."

  opt :org, "The organization to reenable workflows in", :type => :string, :required => true
  opt :extra_repos, "Extra repos to reenable workflows in", :type => :strings, :default => []

  MultiRepo::CLI.common_options(self, :only => :dry_run)
end

github = MultiRepo::Service::Github.new(**opts.slice(:dry_run))

repos = (github.org_repo_names(opts[:org]) + opts[:extra_repos]).sort
repos.each do |repo_name|
  puts MultiRepo::CLI.header(repo_name)

  disabled_workflows = github.disabled_workflows(repo_name)
  if disabled_workflows.any?
    disabled_workflows.each do |w|
      puts "** Enabling #{w.html_url} (#{w.id})"
      github.enable_workflow(repo_name, w.id)
    end
  else
    puts "** No disabled workflows found"
  end

  puts
end
