#!/usr/bin/env ruby

require "bundler/inline"
gemfile do
  source "https://rubygems.org"
  gem "multi_repo", require: "multi_repo/cli", path: File.expand_path("..", __dir__)
end

opts = Optimist.options do
  synopsis "List all repos in a repo set."

  MultiRepo::CLI.common_options(self, :only => :repo_set)
end

puts MultiRepo::CLI.repos_for(**opts).collect(&:name)
