#!/usr/bin/env ruby

require "bundler/inline"
gemfile do
  source "https://rubygems.org"
  gem "multi_repo", require: "multi_repo/cli", path: File.expand_path("..", __dir__)
end

opts = Optimist.options do
  synopsis "List all repos in an org."

  opt :org, "The org to list the repos for", :type => :string, :required => true

  opt :include_forks, "Include forked repos", :default => false
  opt :include_archived, "Include archived repos", :default => false
end

puts MultiRepo::Service::Github.org_repo_names(opts[:org], **opts.slice(:include_forks, :include_archived))
